---
title: "Bayesian Network Diagram through visNetwork"
author: "Ed Sherwood <esherwood@tbep.org>"
date: "July 21, 2017"
output: html_document
---

```{r setup, include=FALSE}
library(visNetwork)
knitr::opts_chunk$set(echo = TRUE)
```

## Develop a Simple Diagram to Illustrate the Bayesian Network
```{r}
nodes <- data.frame(id=1:39, 
                    label = c("Dredging", "Exotic Control", "FW Wetlands", 
                              "Hydrologic Restoration", "Management", "Mangroves", 
                              "Oyster Habitat", "Salt Marsh", "Seagrass", "Uplands", 
                              "Acquisition", "Education", "Protection or Managment", 
                              "Atmospheric Deposition", "Agricultural BMP", 
                              "Alum Treatment BMP", "Baffle Box BMP", "CDS Unit BMP",
                              "SW Management", "Stormwater Pond BMP", "Treatment Train BMP", 
                              "Wetland Treatment BMP", "Stormwater Education", "Stormwater Regulation", 
                              "Send NPS to WWTP", "Street Sweeping", "On Site BMP", "Increase Reuse", 
                              "PS Managment", "Additional PS Treatment", "PS Regulation", 
                              "Habitat Enhancement", "Habitat Establishment", "Habitat Protection", 
                              "Stormwater Control", "Point Source Control", "Salinity", "Dissolved Oxygen",
                              "Chlorophyll-a"), 
                    group = c(rep("Technology", 31), rep("Activity", 5), 
                              rep("WQ Response",3)),
                    level = c(rep(1, 31), rep(2, 5), rep(3, 2), rep(4, 1)),
                    shape = c(rep("ellipse", 31), rep("square", 5), rep("circle", 3)),
                    color = c(rep("red", 31), rep("lightblue", 5), rep("lightgreen",3 ))
                    )                  
edges <- data.frame(from= c(1, 2, 3, 3, 4, 5, 6, 6, 7, 7, 8, 8, 9, 9, 10, 10, 11, 12,
                            13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
                            28, 29, 30, 31, 32, 32, 32, 33, 33, 33, 34, 34, 34, 35, 35,
                            35, 36, 36, 36, 37, 37, 38), 
                    to = c(32, 32, 32, 33, 32, 32, 32, 33, 32, 33, 32, 33, 32, 33, 32, 
                           33, 34, 34, 34, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
                           35, 35, 36, 36, 36, 36, 36, 37, 38, 39, 37, 38, 39, 37, 38,
                           39, 37, 38, 39, 37, 38, 39, 38, 39, 39)
)
visNetwork(nodes, edges, main = "Group 1: Bayesian Network Skeleton", width = "100%") %>%
  visEdges(arrows = "to") %>%
  visGroups(groupname = "Technology", color = "red", shape = "ellipse") %>%
  visGroups(groupname = "Activity", color = "lightblue", shape = "square") %>% 
  visGroups(groupname = "WQ Response", color = list(background= "white", border= "black"), shape = "circle") %>%
  visLegend(main = "Bayesian Parameter") %>%
  visHierarchicalLayout() # same as   visLayout(hierarchical = TRUE) 
```
